name: Generate API Code

on:
  push:
    branches:
      - main

jobs:
  generate_api_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate API Code
      uses: docker://openapitools/openapi-generator-cli:v3.0.3
      with:
        args: generate -i openapi.yaml -g go -o generated-code

    - name: Commit Generated Code
      run: |
        git config --local user.email "smcoolsam44@gmail.com"
        git config --local user.name "Sam12121"
        git add generated-code
        git commit -m "Generate API code"
        git push
